#!/usr/bin/env bash

# Use pandoc to generate PDF or EPUB from markdown document.
##
# Sahri Riza Umami
#   v0.1 - 2023-01-04 08:40:35
#        - Initial release
#
# LICENSE ----------------------------------------------------------------------
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org>
#
# ------------------------------------------------------------------------------

# Checking dependencies:
declare -a DEPS=(pandoc)
for ((NUM=${#DEPS[@]},i=0; i<NUM;i++)); do
  if command -v "${DEPS[i]}" &>/dev/null ; then
    unset -v 'DEPS[i]'
  fi
done

# Exit if dependency not found.
if [[ "${#DEPS[@]}" -gt 0 ]]; then
  printf '\e[31m!! %s\n\e[m' 'Package(s) not found'
  printf '\e[33m:: %s\n\e[m' 'Install the proper distribution package for your system:'
  printf '   - %s\n' "${DEPS[@]}"
  exit 1
fi

# VARIABLES --------------------------------------------------------------------

# FUNCTIONS --------------------------------------------------------------------

print_usage() {
  printf '%s\n' "
  ${0##*/} will create EPUB or PDF from markdown documents.

  Usage: ${0##*/} EBOOK_FORMAT

  EBOOK_FORMAT:
    epub    Electronic Publication. Mostly used on small screen devices.
    pdf     Portable Document Format. What you see is what get on print.

  Example:
    - ${0##*/} epub
    - ${0##*/} pdf
"
  exit
}

# MAIN -------------------------------------------------------------------------

case $1 in
  epub)
    pandoc -s --toc UnleashX.md assets/epub-meta.yaml -o UnleashX.epub
  ;;
  pdf)
    # https://jdhao.github.io/2019/05/30/markdown2pdf_pandoc/
    pandoc  --pdf-engine=xelatex \
            --highlight-style zenburn \
            -f markdown-raw_tex \
            --toc \
            -N \
            -V colorlinks \
            -V urlcolor=NavyBlue \
            -V toccolor=red \
            -V papersize:a4 \
            -V subparagraph \
            -H assets/head.tex \
            -o UnleashX.pdf UnleashX.md
  ;;
  *)
    print_usage
  ;;
esac
